#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080
#define FPS_DELAY 17
#define ANIMATION_LOOP 4
#define MAP_SIZE 600
#define CASE_SIZE 120
#define CASE_OFFSET_X (WINDOW_WIDTH-MAP_SIZE)/2+CASE_SIZE/6
#define CASE_OFFSET_Y (WINDOW_HEIGHT-MAP_SIZE)/2+CASE_SIZE/6
#define SPRITE_SIZE CASE_SIZE/2 + 20
#define FIREBALL_MOVELOOP 1
#define FIREBALL_SPEED 7
#define OBSTACLE_WARNING 50
#define WIDGET_LENGTH 48
#define END_SCORE_SIZE 20
#define SCORE_SIZE 25
#define MONEY_SIZE 20
#define PLAYER_MOVE 10
#define SKIN_W_H 120
#define SKIN_X_Y WINDOW_WIDTH / 2 - 60

#endif
